<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationIcon>shootergame.ico</ApplicationIcon>
	<SelfContained>true</SelfContained>
	<RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <PublishSingleFile>true</PublishSingleFile>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Resources\BackgroundGame1.png" />
    <None Remove="Resources\BackgroundGame2.png" />
    <None Remove="Resources\BackgroundLeaderboard.png" />
    <None Remove="Resources\BackgroundLogin.png" />
    <None Remove="Resources\BackgroundMenu.png" />
    <None Remove="Resources\BackgroundRegister.png" />
    <None Remove="Resources\BackgroundRegister1.png" />
    <None Remove="Resources\BulletEnemy.png" />
    <None Remove="Resources\BulletFairyPic.png" />
    <None Remove="Resources\BulletOldmanPic.png" />
    <None Remove="Resources\BulletSoldierPic.png" />
    <None Remove="Resources\EnemyFrame1.png" />
    <None Remove="Resources\EnemyFrame2.png" />
    <None Remove="Resources\EnemyFrame3.png" />
    <None Remove="Resources\EnemyHP1.png" />
    <None Remove="Resources\EnemyHP10.png" />
    <None Remove="Resources\EnemyHP11.png" />
    <None Remove="Resources\EnemyHP12.png" />
    <None Remove="Resources\EnemyHP13.png" />
    <None Remove="Resources\EnemyHP14.png" />
    <None Remove="Resources\EnemyHP15.png" />
    <None Remove="Resources\EnemyHP2.png" />
    <None Remove="Resources\EnemyHP3.png" />
    <None Remove="Resources\EnemyHP4.png" />
    <None Remove="Resources\EnemyHP5.png" />
    <None Remove="Resources\EnemyHP6.png" />
    <None Remove="Resources\EnemyHP7.png" />
    <None Remove="Resources\EnemyHP8.png" />
    <None Remove="Resources\EnemyHP9.png" />
    <None Remove="Resources\FairyFrame1.png" />
    <None Remove="Resources\FairyFrame2.png" />
    <None Remove="Resources\FairyFrame3.png" />
    <None Remove="Resources\FairyFrame4.png" />
    <None Remove="Resources\FairyFrame5.png" />
    <None Remove="Resources\FairyFrame6.png" />
    <None Remove="Resources\FairyHPBar1.png" />
    <None Remove="Resources\FairyHPBar2.png" />
    <None Remove="Resources\FairyHPBar3.png" />
    <None Remove="Resources\FairyHPBar4.png" />
    <None Remove="Resources\FairyHPBar5.png" />
    <None Remove="Resources\FairyHPBar6.png" />
    <None Remove="Resources\FairyHPBar7.png" />
    <None Remove="Resources\FairyHPBar8.png" />
    <None Remove="Resources\FairyHPBar9.png" />
    <None Remove="Resources\OldmanFrame1.png" />
    <None Remove="Resources\OldmanFrame2-3.png" />
    <None Remove="Resources\OldManFrame4.png" />
    <None Remove="Resources\OldmanFrame5.png" />
    <None Remove="Resources\OldmanFrame6.png" />
    <None Remove="Resources\OldmanHP1.png" />
    <None Remove="Resources\OldmanHP2.png" />
    <None Remove="Resources\OldmanHP3.png" />
    <None Remove="Resources\OldmanHP4.png" />
    <None Remove="Resources\SoldierFrame1.png" />
    <None Remove="Resources\SoldierFrame2.png" />
    <None Remove="Resources\SoldierFrame3.png" />
    <None Remove="Resources\SoldierFrame4.png" />
    <None Remove="Resources\SoldierFrame5.png" />
    <None Remove="Resources\SoldierFrame6.png" />
    <None Remove="Resources\SoldierHP1.png" />
    <None Remove="Resources\SoldierHP2.png" />
    <None Remove="Resources\SoldierHP3.png" />
    <None Remove="Resources\SoldierHP4.png" />
    <None Remove="Resources\SoldierHP5.png" />
    <None Remove="Resources\SoldierHP6.png" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Resources\BackgroundGame1.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\BackgroundGame2.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\BackgroundLeaderboard.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\BackgroundLogin.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\BackgroundMenu.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\BackgroundRegister.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\BackgroundRegister1.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\BulletEnemy.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\BulletFairyPic.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\BulletOldmanPic.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\BulletSoldierPic.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\EnemyFrame1.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\EnemyFrame2.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\EnemyFrame3.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\EnemyHP1.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\EnemyHP10.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\EnemyHP11.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\EnemyHP12.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\EnemyHP13.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\EnemyHP14.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\EnemyHP15.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\EnemyHP2.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\EnemyHP3.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\EnemyHP4.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\EnemyHP5.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\EnemyHP6.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\EnemyHP7.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\EnemyHP8.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\EnemyHP9.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\FairyFrame1.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\FairyFrame2.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\FairyFrame3.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\FairyFrame4.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\FairyFrame5.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\FairyFrame6.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\FairyHPBar1.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\FairyHPBar2.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\FairyHPBar3.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\FairyHPBar4.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\FairyHPBar5.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\FairyHPBar6.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\FairyHPBar7.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\FairyHPBar8.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\FairyHPBar9.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\OldmanFrame1.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\OldmanFrame2-3.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\OldManFrame4.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\OldmanFrame5.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\OldmanFrame6.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\OldmanHP1.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\OldmanHP2.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\OldmanHP3.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\OldmanHP4.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\SoldierFrame1.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\SoldierFrame2.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\SoldierFrame3.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\SoldierFrame4.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\SoldierFrame5.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\SoldierFrame6.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\SoldierHP1.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\SoldierHP2.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\SoldierHP3.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\SoldierHP4.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\SoldierHP5.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\SoldierHP6.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="shootergame.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.12" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

</Project>